plugins {
	id 'java'
	id 'org.springframework.boot' version '3.3.4'
	id 'io.spring.dependency-management' version '1.1.6'
}

group = 'com.wietos'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
	}
}

repositories {
	mavenCentral()
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter'
	implementation 'org.springframework.boot:spring-boot-devtools'
	implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-thymeleaf'
	implementation 'org.springframework.boot:spring-boot-starter-data-mongodb'

	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('test') {
	useJUnitPlatform()
}

tasks.register('copyLibs', Copy) {
	from "$projectDir/build/libs"
	include '*.jar'
	into "$projectDir/libs"
	doLast {
		println "Copied JAR files to libs directory."
		exec {
			commandLine 'git', 'add', 'libs/'
			standardOutput = System.out
			errorOutput = System.err
		}
	}
}

tasks.named('jar') {
	finalizedBy 'copyLibs'
}
tasks.named('bootJar') {
	finalizedBy 'copyLibs'
}